name: "Exploit In Progress"
description: "Report an exploiter to staff, do not use if the incident has already concluded."
title: "Exploiting In Progress - [USERNAME HERE]"
labels: "Response Needed: Moderation,Incident Type: Exploiting"
body:
- type: markdown
  value: DO NOT SEND PRIVATE INFORMATION IN THIS FORM. IF YOU NEED TO, TELL STAFF TO CONTACT YOU.
- type: input
  id: exploiterusername
  attributes:
    label: What is the undername of the Exploiter?
    description: "Roblox username, not display name."
    placeholder: "badman0325"
  validations:
    required: true
- type: input
  id: reporter
  attributes:
    label: What is your username?
    description: "Username, not display name."
    placeholder: "badman009"
  validations:
    required: true
- type: input
  id: contact
  attributes:
    label: Contact
    description: How can we contact you if we need more details?"
    placeholder: "Discord: Example#0000"
- type: input
  id: location
  attributes:
    label: Where did this occur?
    description: What game / place.
    placeholder: "Naval Warfare Remastered"
  validations:
    required: true
- type: textarea
  id: notes
  attributes:
    label: Is there anything else the responding staff should be aware of?
    description: "What they are doing, how serious, etc."
